language: objective-c
osx_image: xcode12
script:
  - xcodebuild -scheme DekaExtensions-Package -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 11' test
branches:
  only:
  - develop
  - /\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  slack: 
    if: tag IS present
    rooms:
      dekalabs:5fKxbA5KgdU9mKMZkM1Ff5nb#tech_ios
    template:
      - "%{repository_slug} (%{commit}) : %{message}, by %{author}"
      - "New Version Released: %{tag}"
