language: objective-c
osx_image: xcode12
script:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; 
    then xcodebuild -scheme DekaExtensions-Package -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 11' test; 
    fi
branches:
  only:
  - develop
  - main
  - /\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  slack: 
    # if: tag IS present
    rooms: dekalabs:5fKxbA5KgdU9mKMZkM1Ff5nb#travis_ci
    template:
      - "%{repository_slug} (%{commit}) : %{message} by %{author}. Version $TRAVIS_TAG, %{build_number}, %{build_id}, %{build_url}, %{branch}"
      - "New Version Released:" + "$TRAVIS_TAG"
