language: objective-c
osx_image: xcode12
script:
  - xcodebuild -scheme DekaExtensions-Package -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 11' test
branches:
  only:
  - develop
notifications:
  slack:
    rooms:
	  - dekalabs:5fKxbA5KgdU9mKMZkM1Ff5nb#tech_ios
